### ISSUE TITLE
Forking this for my community

### ISSUE THREAD

**Issue by NatVIII** [ivyraine/bay.lgbt#7]
Hey Ivy!

New T-Girlie checking in wanting to host this for her local area. I love anarchism.nyc, but I wanna try and fork this for my local area (Richmond, Virginia). I especially love that you have it compatible with reading Instagram posts (please stop posting your events to instagram x100).

Is there a guide or would you be willing to help me get a fork running for my local community? Starting with zero experience in npm, but I've been doing projects like this for years, I can figure my way out.

Thanks mwah <3

**Comment by ivyraine** [comment]
I'm thrilled you're trying this out (my hope is that every city has their own .lgbt or equivalent). There isn't a guide- would you be willing to write one as you boot it up? I'm swamped with work these days. I can probably help out here and there- send me an email at mail(at)virtual.gf and we can correspond there.

**Comment by NatVIII** [comment]
Sounds good :heart:
